#!/usr/bin/env python3
"""Generate src/worldPaths.js, the outline behind the photo map.

    npm run gen:map

Source is Natural Earth 110m land, which is public domain. The projection
window is cropped to the part of the world the photos are actually in: a whole
globe would be mostly empty ocean, and it would also read as a travel brag
rather than a filter control.

Rerun this only if the window changes. It prints the projected position of
every group afterwards, which is what MAP_POINTS in src/constants/index.js
holds; those need updating by hand at the same time, because the label offsets
next to them are placed by eye.
"""
import json
import math
import os
import urllib.request

SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
    "geojson/ne_110m_land.geojson"
)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "worldPaths.js")
CACHE = os.path.join(ROOT, "scripts", ".ne_110m_land.geojson")

LON0, LON1 = -125.0, 28.0
LAT0, LAT1 = 7.0, 57.5
W = 1000.0
TOL = 0.9  # simplification tolerance, in projected units

# Where each group's dot goes. City level on purpose: some of these photos were
# taken at home, and a public site should not draw a ring round anyone's house.
GROUPS = {
    "massachusetts": (42.36, -71.06),
    "new-york": (40.75, -73.98),
    "arkansas": (35.90, -93.60),
    "southwest": (37.20, -111.80),
    "costa-rica": (10.20, -84.50),
    "ireland": (52.60, -8.60),
    "sicily": (37.60, 14.90),
}


def merc_y(lat):
    lat = max(min(lat, 84.0), -84.0)
    return math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))


Y0, Y1 = merc_y(LAT0), merc_y(LAT1)
H = W * (Y1 - Y0) / math.radians(LON1 - LON0)


def project(lon, lat):
    return (
        (lon - LON0) / (LON1 - LON0) * W,
        (Y1 - merc_y(lat)) / (Y1 - Y0) * H,
    )


def rdp(pts, tol):
    """Ramer-Douglas-Peucker. The 110m data is coarse already, but dropping
    near-collinear runs roughly halves the emitted file."""
    if len(pts) < 3:
        return pts
    ax, ay = pts[0]
    bx, by = pts[-1]
    dx, dy = bx - ax, by - ay
    n = math.hypot(dx, dy)
    worst, idx = -1.0, 0
    for i in range(1, len(pts) - 1):
        px, py = pts[i]
        d = (
            abs(dy * px - dx * py + bx * ay - by * ax) / n
            if n
            else math.hypot(px - ax, py - ay)
        )
        if d > worst:
            worst, idx = d, i
    if worst <= tol:
        return [pts[0], pts[-1]]
    return rdp(pts[: idx + 1], tol)[:-1] + rdp(pts[idx:], tol)


def rings(geom):
    if geom["type"] == "Polygon":
        return [geom["coordinates"][0]]
    if geom["type"] == "MultiPolygon":
        return [poly[0] for poly in geom["coordinates"]]
    return []


def main():
    if not os.path.exists(CACHE):
        print(f"downloading {SOURCE}")
        urllib.request.urlretrieve(SOURCE, CACHE)

    paths = []
    for feat in json.load(open(CACHE))["features"]:
        for ring in rings(feat["geometry"]):
            lons = [c[0] for c in ring]
            lats = [c[1] for c in ring]
            if (
                max(lons) < LON0 or min(lons) > LON1
                or max(lats) < LAT0 or min(lats) > LAT1
            ):
                continue
            pts = rdp([project(lon, lat) for lon, lat in ring], TOL)
            if len(pts) < 4:
                continue
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            # Drop specks: anything smaller than a map dot is just noise.
            if (max(xs) - min(xs)) < 6 and (max(ys) - min(ys)) < 6:
                continue
            paths.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z")

    with open(OUT, "w") as fh:
        fh.write(
            "/* Generated by scripts/gen-map.py from Natural Earth 110m land\n"
            " * (public domain). Do not edit by hand.\n"
            f" * Mercator, cropped to lon {LON0}..{LON1}, lat {LAT0}..{LAT1}.\n"
            " */\n"
            f"export const MAP_WIDTH = {W:.0f};\n"
            f"export const MAP_HEIGHT = {H:.1f};\n\n"
            "export const LAND = [\n"
        )
        for d in paths:
            fh.write(f'  "{d}",\n')
        fh.write("];\n")

    print(f"{len(paths)} paths, viewBox 0 0 {W:.0f} {H:.1f}")
    print("\nMAP_POINTS x/y for src/constants/index.js:")
    for slug, (lat, lon) in GROUPS.items():
        x, y = project(lon, lat)
        print(f"  {slug:>14}: x {x:6.1f}  y {y:6.1f}")


if __name__ == "__main__":
    main()
